FROM node:22.12.0-bookworm AS base
ENV NODE_ENV=development
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

COPY . .

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
  pnpm install --prefer-offline --frozen-lockfile --unsafe-perm

CMD ["./docker/docker-entrypoint.dev.sh"]