services:
  postgres:
    container_name: sw-api-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 'sw-api'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_sw_api:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d sw-api']
      start_interval: 30s
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_sw_api:
